# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=11, verbose_name='Telefon Numarası')),
                ('cinsiyet', models.CharField(blank=True, default=3, max_length=1, verbose_name='Cinsiyet')),
                ('dogum', models.DateField(blank=True, verbose_name='Doğum tarihi')),
                ('profil_photo', models.ImageField(upload_to=users.models.upload_to, verbose_name='Profil Fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
    ]
