# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kız'), ('O', 'Other')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
