# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180213_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dogum',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefon_numarasi',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
