# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0002_auto_20180126_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kategoriler',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_date'], 'verbose_name': 'Görevler', 'verbose_name_plural': 'Görevler'},
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonetim.Category', verbose_name='Kategori'),
        ),
    ]
