# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0003_auto_20180126_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='yonetim.Category'),
        ),
    ]
