# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0005_auto_20180126_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Durum',
                'verbose_name_plural': 'Durum',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ManyToManyField(to='yonetim.Status'),
        ),
    ]
