# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0008_auto_20180128_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Belge'),
        ),
    ]
