# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0009_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Resim'),
        ),
    ]
