# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0010_auto_20180203_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='selam', max_length=202, unique=True, verbose_name='Slug Alanı'),
            preserve_default=False,
        ),
    ]
