# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0011_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(editable=False, max_length=202, unique=True, verbose_name='Slug Alanı'),
        ),
    ]
