# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0012_auto_20180204_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='', max_length=202, unique=True, verbose_name='Slug Alanı'),
        ),
    ]
