# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import yonetim.models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0013_auto_20180204_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to=yonetim.models.upload_to, verbose_name='Resim'),
        ),
    ]
