# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0016_assingusertotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yonetim.Task')),
            ],
            options={
                'verbose_name': 'Görevler1',
                'verbose_name_plural': 'Görevler1',
                'ordering': ['-created_date'],
            },
            bases=('yonetim.task',),
        ),
    ]
