# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yonetim', '0017_task1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan'),
        ),
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
