# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0018_auto_20180208_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
    ]
